--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4
-- Dumped by pg_dump version 15.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_clientes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clientes_clientes (
    id bigint NOT NULL,
    cliente integer NOT NULL,
    tipo character varying(1) NOT NULL,
    nombre character varying(150) NOT NULL,
    telefono character varying(150) NOT NULL,
    correo character varying(150) NOT NULL,
    direccion character varying(250) NOT NULL,
    paginaweb character varying(150) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    estado character varying(1) NOT NULL,
    empresa_id bigint NOT NULL
);


ALTER TABLE public.clientes_clientes OWNER TO postgres;

--
-- Name: clientes_clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clientes_clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: det_factura_detfactura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.det_factura_detfactura (
    id bigint NOT NULL,
    consecutivo integer NOT NULL,
    cantidad numeric(20,2) NOT NULL,
    precio numeric(20,2) NOT NULL,
    subtotal numeric(20,2) NOT NULL,
    empresa_id bigint NOT NULL,
    id_factura_id bigint NOT NULL,
    id_producto_id bigint NOT NULL
);


ALTER TABLE public.det_factura_detfactura OWNER TO postgres;

--
-- Name: det_factura_detfactura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.det_factura_detfactura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.det_factura_detfactura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: empresa_empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa_empresa (
    id bigint NOT NULL,
    empresa integer NOT NULL,
    nombre character varying(150) NOT NULL,
    estado character varying(1) NOT NULL
);


ALTER TABLE public.empresa_empresa OWNER TO postgres;

--
-- Name: empresa_empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa_empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mae_factura_maefactura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mae_factura_maefactura (
    id bigint NOT NULL,
    numero integer NOT NULL,
    fehca_creacion timestamp with time zone NOT NULL,
    observaciones character varying(300) NOT NULL,
    total numeric(20,2) NOT NULL,
    fecha_auditoria timestamp with time zone NOT NULL,
    cliente_id bigint NOT NULL,
    empresa_id bigint NOT NULL
);


ALTER TABLE public.mae_factura_maefactura OWNER TO postgres;

--
-- Name: mae_factura_maefactura_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mae_factura_maefactura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mae_factura_maefactura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos_productos (
    id bigint NOT NULL,
    producto character varying(30) NOT NULL,
    nombre character varying(150) NOT NULL,
    tipo character varying(1) NOT NULL,
    fotoproducto character varying(100) NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    estado character varying(1) NOT NULL,
    empresa_id bigint NOT NULL
);


ALTER TABLE public.productos_productos OWNER TO postgres;

--
-- Name: productos_productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos_productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add empresa	7	add_empresa
26	Can change empresa	7	change_empresa
27	Can delete empresa	7	delete_empresa
28	Can view empresa	7	view_empresa
29	Can add clientes	8	add_clientes
30	Can change clientes	8	change_clientes
31	Can delete clientes	8	delete_clientes
32	Can view clientes	8	view_clientes
33	Can add productos	9	add_productos
34	Can change productos	9	change_productos
35	Can delete productos	9	delete_productos
36	Can view productos	9	view_productos
37	Can add det factura	10	add_detfactura
38	Can change det factura	10	change_detfactura
39	Can delete det factura	10	delete_detfactura
40	Can view det factura	10	view_detfactura
41	Can add mae factura	11	add_maefactura
42	Can change mae factura	11	change_maefactura
43	Can delete mae factura	11	delete_maefactura
44	Can view mae factura	11	view_maefactura
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$390000$eCBmB2ONAoDsvwy28AXKNr$r28OWwD2eK9O/v/8jHp0kJ9nWRT67YpnyFCah4YRdSU=	2024-07-10 22:37:15.34466-05	t	admin			stromcaceres4@gmail.com	t	t	2024-07-10 11:45:15.842235-05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: clientes_clientes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clientes_clientes (id, cliente, tipo, nombre, telefono, correo, direccion, paginaweb, fecha_creacion, estado, empresa_id) FROM stdin;
1	1007952577	C	Erik Santiago	3185234358	stromcaceres4@gmail.com	cll 6 # 1-44 int 21	paginaweb.com	2024-07-10 19:37:36.700996-05	A	4
2	830003564	N	ENTIDAD PROMOTORA DE SALUD FAMISANAR S.A.S.	.	.	 CL 78 13 A 07		2022-06-23 00:00:00-05	A	1
3	830003564	N	ENTIDAD PROMOTORA DE SALUD FAMISANAR S.A.S.	.	.	 CL 78 13 A 07		2022-06-23 00:00:00-05	A	1
4	901131909	N	TERNIUM DEL ATLANTICO SAS	.	KLARIOS@TERNIUM.COM.CO	 CR 42 26 18		2022-09-07 00:00:00-05	A	1
5	900174468	N	TERNIUM SIDERURGICA DE CALDAS S.A.S.	.	KLARIOS@TERNIUM.COM.CO	 CR 42 26 18		2022-09-13 00:00:00-05	A	1
6	800189687	N	ACEROS CORTADOS S.A.S	.	MYEINVOICE@GRUPOCNET.NET	 CR TRONCAL DEL OCCIDENTE SAN C FUNZA		2022-09-13 00:00:00-05	A	1
7	817000865	N	METALSUR S.A	.	FSARMIENTO@FANALCA.COM	 PARQUE COMERCIAL DE CAUCA ETAPA 3  LOTE 4		2022-09-13 00:00:00-05	A	1
8	890301886	N	FANALCA S.A	.	FSARMIENTO@FANALCA.COM	 CL 72 5 83 OFICINA  302		2022-09-13 00:00:00-05	A	1
9	901281934	N	CEMENTOS DEL ORIENTE S.A.S ZOMAC	3174302620	MIRYANNARANJO@ORIENTTE.CO	 CL 15 21 05		2022-09-13 00:00:00-05	A	1
10	800219247	N	ACERRIOS MONTE VERDE	.	.	 CL 29 46 A		2022-09-23 00:00:00-05	A	1
11	800138188	N	ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIA PROTECCION S.A.	 315 7133166	SEGURINFO@PROTECCION.COM.CO	 CL 49 63 100		2022-06-23 00:00:00-05	A	1
12	800149496	N	COLFONDOS S.A. PENSIONES Y CESANTIAS	3007485245	PROCESOSJUDICIALES@COLFONDOS.COM.CO	 AC 30 85 16		2022-06-23 00:00:00-05	A	1
13	800170043	N	FONDO DE CESANTIAS PORVENIR	3112742152	 ABC@PORVENIR.COM.CO	 CR 13 26 A 56		2022-06-23 00:00:00-05	A	1
14	899999284	N	FONDO NACIONAL DEL AHORRO - CARLOS LLERAS RESTREPO	3103072512	GERENCIA@FONDONACIONALDELAHORRO.CO	 CR 65 11 83		2022-06-23 00:00:00-05	A	1
15	860003020	N	BANCO BILVAO VISCAYA ARGENTARIA COLOMBIA	 630 40 00	ADMINISTRACIONGERENCIAL@BBVA.COM	 CR 9 72 21		2022-06-23 00:00:00-05	A	1
16	860007738	N	BANCO POPULAR S.A.	.	.	 CL 17 7 43		2022-06-23 00:00:00-05	A	1
17	860034594	N	BANCO SCOTIABANK COLPATRIA S.A.	.	.	 AC 26 69 63		2022-06-23 00:00:00-05	A	1
18	800148514	N	SKANDIA ADMINISTRADORA DE FONDOS DE PENSIONES Y CESANTIAS S.A.	31245125412	GERENCIQWW@SKANDIA.COM	 AC 19 109 A		2022-06-23 00:00:00-05	A	1
19	860002964	N	BANCO DE BOGOT�	.	.	 CL 36 7 47 LC		2022-06-23 00:00:00-05	A	1
20	800037800	N	BANCO AGRARIO DE COLOMBIA S.A.	.	.	 CR 8 15 43		2022-06-23 00:00:00-05	A	1
21	860007335	N	BANCO CAJA SOCIAL S.A.	.	.	 CR 7 77 65 LC 9		2022-06-23 00:00:00-05	A	1
22	860050750	N	BANCO GNB SUDAMERIS S.A.	.	.	 CR 8 15 42		2022-06-23 00:00:00-05	A	1
23	43168677	C	NUBIA SOREYY NARANJO BETANCUR	3043779875	SOREY.COMERCIAL@GMAIL.COM	 CR 62 A 74 SUR 164		2022-09-23 00:00:00-05	A	1
24	1110443926	C	ERWIN ANDRES SILVA LARA	3028680330	ENWINANDRES1000@GMAIL.COM	 CR 26 3 77		2022-10-07 00:00:00-05	A	1
25	1048207415	C	HENRY  ARAUJO	.	.	 CL 2 3 70		2022-10-07 00:00:00-05	A	1
26	1124004378	C	OSCAR JULIO	.	.	 CR 12 5 27		2022-10-07 00:00:00-05	A	1
27	890900841	C	CAJA DE COMPENACION FAMILIAR COMFAMA	0	0	 CL 2 SUR 53 82		2022-06-23 00:00:00-05	A	1
28	179247	C	MACEDONIO  MANRIQUE ROMERO	0	manriquemacedonio@gmail.com	VDA SAN ANTONIO		2022-06-23 00:00:00-05	A	1
29	192097	C	FABIO HUMBERTO OSPINA PULIDO	0	kik3ospina@hotmail.com	KR 2 6 32		2022-04-08 00:00:00-05	A	1
30	285923	C	JORGE CASTIBLANCO RODRIGUEZ	3164854205	jorgecastiblanco50@outlook.com	KR 1 1 05 AV PANAMERICANA		2022-04-08 00:00:00-05	A	1
31	506767	C	ENRIQUE ANTONIO PARAMO CORDOBA	7268823	casadelvidrio506@hotmail.com	KR 11 15 04 BRR CENTRO		2022-04-08 00:00:00-05	A	1
32	1013419	C	NESTOR SANCHEZ NESTOR	3138839854	pegarama@hotmail.com	CL 139 140 10		2022-04-08 00:00:00-05	A	1
33	1033352	C	VICTOR CENON ARIAS BERMUDES	0	distibuidoradelnorte@gmail.com	DG 28 7 76		2022-04-08 00:00:00-05	A	1
34	1079856	C	PABLO ENRIQUE ROJAS CORDOBA	6247054	contabilidad@ferrelectricoscentral.com	KR 12 6 28 BRR PALMARITO		2022-04-08 00:00:00-05	A	1
35	1114369	C	LIBARDO JARAMILLO YEPEZ	3114407277	lijaye@hotmail.com	KR 20 A 6 A 28		2022-04-08 00:00:00-05	A	1
36	1160454	C	YUBER ORLANDO ACOSTA ROBERTO	3124564326	ventasdobladoraelperdomo@gmail.com	CL 64 SUR 72 A 73 BRR EL PERDOMO		2022-04-08 00:00:00-05	A	1
37	2183371	C	LUIS DOMINGO GONZALEZ MONSALVE	3657972	feluya26@hotmail.com	KR 26 A 73 C 132		2022-04-08 00:00:00-05	A	1
38	2612992	C	OLIVER BEJARANO HERRERA	3155930202	bufalocc@hotmail.com	CL 15 NORTE 4 NORTE 30		2022-04-08 00:00:00-05	A	1
39	2768438	C	JOSE ALFONSO GUERRA GAMEZ	0	josealfonsoguerragamez@gmail.com	KR 14 13 07		2022-04-08 00:00:00-05	A	1
40	2919550	C	VICTOR JULIO MENDOZA	3156497189	indumetalicasvimen@hotmail.com	CL 79 61 59		2022-04-08 00:00:00-05	A	1
41	2971263	C	ALVARO FIGUEROA CARRE�O	3144738003	figueroacarre�o@gmail.com	KR 12 11 52 BR LA DESPENSA		2022-04-08 00:00:00-05	A	1
42	2971684	C	JAIME NARVAEZ BONILLA	7628842	dpositonarvaez@gmail.com	KR 7 ESTE 90 D 46		2022-04-08 00:00:00-05	A	1
43	830136799	N	BIOMAX SA  .	6013798000	SERVICIOALCLIENTE@BIOMAX.CO	CR 14 99 33 P 9		2023-05-04 00:00:00-05	A	3
44	900235157	N	COMPU IMPRESION SAS  .	318 527 5783	VENTAS@COMPUIMPRESION.COM.CO	 CR A 15 77 05 L 1 60		2023-06-05 00:00:00-05	A	3
45	900346376	N	MULTISERVICIOS SUMIREPUESTOS S.A.S	3143317053	MULTISERVICIOSSAS@GMAIL.COM	 CL 11 28 179		2023-02-03 00:00:00-05	A	3
46	900755245	N	CONSTRUCCIONES Y FABRICACIONES DE INGENIERA SAS	3144115783	JOSEHURTADO.COMERCIAL@GMAIL.COM	DG 59 11A 100		2023-06-27 00:00:00-05	A	3
47	901076058	N	FUNDICION HERMANOS SANCHEZ Y PARRA S.A.S	3176566638	.	KM 1 VIA TUNJA HACIA VILLA DE LEYVA		2023-07-22 00:00:00-05	A	3
48	830109078	N	TRANSMISION MECANICA SAS	8966893	CONTABILIDAD@TRAMECLTDA.COM	AUT MEDELLIN K M 25 ENTRADA PARCELAS		2023-05-11 00:00:00-05	A	3
49	860514851	N	DISCORREAS MANGUERAS Y EMPAQUES SA	3164681289	CONTABILIDAD@DISCORREAS.COM	cll 13 bn 27-02		2023-03-03 00:00:00-05	A	3
50	79917615	N	JAIRO LUIS QUIJANO SANCHEZ	3115437398	auditoriapso@gmail.com	 CL 12 52 11		2023-03-23 00:00:00-05	A	3
51	438493	N	JUAN GUILLERMO BOTERO DIAZ	.	JGB_RANCH@HOTMAIL.COM	CR 55 79 A 65 BRR GAITAN		2023-02-07 00:00:00-05	A	3
52	2202840	N	EFRAIN ARIZA MATEUS	.	edselsurtidor@yahoo.com	CL 5 5 27		2023-02-07 00:00:00-05	A	3
53	43365615	C	FERRETERIA LA UNICA SOGAMOSO	7704204	.	CALLE 11 NO 16-33		2023-01-06 00:00:00-05	A	3
54	72099041	C	JAIRO ALONSO REALES RODRIGUEZ	3108497477	jreales841@gmail.com	 CL 21 12 52 AP		2023-01-20 00:00:00-05	A	3
55	46455894	C	CLAUDIA JAZMIN ROSAS BAEZ	3123501427	claudiarosas1207@gmail.com	 CR 40 21 48		2023-02-08 00:00:00-05	A	3
56	1053585385	C	LINA JOHANA NOVA NU�EZ	3125935405	ljcln10@gmail.com	 CR 5 7 77		2023-05-11 00:00:00-05	A	3
57	23583112	C	BRENDA ALEJANDRA PATARROYO COY	3143428643	AUDITORIA@ORIENTTE.CO	CR 4 5 A 55		2023-03-11 00:00:00-05	A	3
58	32769850	C	GRACE  MARTINEZ DOMINGUEZ	3007984400	0	.		2023-06-30 00:00:00-05	A	3
59	37900024	C	YAQUELINE  BUENO HERRERA	3016282384	YACQUEBUENO25@HOTMAIL.COM	CL 35 A 8 G 23		2023-06-30 00:00:00-05	A	3
60	32786098	C	ELIANA CRISTINA GONZALEZ LOBELO	3006282284	CRISTINAGONZALEZ@GMAIL.COM	.		2023-06-30 00:00:00-05	A	3
61	32675316	C	LILIANA MARGARITA CABALLERO CANTILLO	3182216153	margaritacc2507@gmail.com	 CL 6 13 42 AP		2023-02-08 00:00:00-05	A	3
62	46358359	C	MYRIAM  CHAPARRO PEREZ	3114964623	myriamchaparro@orientte.co	 CL 38 10 A 130		2023-02-08 00:00:00-05	A	3
63	91449487	N	RAUL  AMAYA TORRES	8331901	FERRETERIAELINDUSTRIAL@YAHOO.COM	CRA 1 E No 54A-08		2023-03-24 00:00:00-05	A	2
64	91478413	N	LEAL OLEJUA JOSE ALEJANDRO	3166539566	alejotubosytubos@hotmail.com	CR 13 24 44		2022-09-21 00:00:00-05	A	2
65	91498024	N	FUENTES NI�O PEDRO ADOLFO	4140400	ferreterialacasadelalba@hotmail.com	CL 3 9A 24		2022-09-21 00:00:00-05	A	2
66	91506876	N	CARRE�O NI�O HENRY MAURICIO	3118860580	hmcarrenon@gmail.com	CL 12 A 2026 AP 101		2022-09-21 00:00:00-05	A	2
67	92095860	N	NAVARRO OLMOS JORGE LUIS	3126422533	josediazmel@hotmail.com	CR 16 10 48		2022-09-21 00:00:00-05	A	2
68	92256201	N	REYES THERAN IVAN ARTURO	2838022	servimateriales@hotmail.com	C.C. REAL 27 60		2022-09-21 00:00:00-05	A	2
69	92259495	N	CRUZ HERRERA AMAURY ENRIQUE/// FERRETERIA TAKAZUAN	3126160672	amaurycruz.7@gmail.com	CL 19 7 74		2023-01-04 00:00:00-05	A	2
70	92520165	N	CALDERA SERPA ELMIS ALFONSO	2751426	.	CL 25 8 C 488		2022-09-21 00:00:00-05	A	2
71	93126601	N	BRI�EZ AVILA JOSE ERNESTO	2487965	distribuidorajeba@hotmail.com	CR 8A 16 05		2023-05-23 00:00:00-05	A	2
72	93131413	N	CONDE LUNA MAURICIO/ M&T FERRECONDE	2889133	facturacionferreconde@hotmail.com	CRA 15 No 45-21 Br. Palermo		2022-09-21 00:00:00-05	A	2
73	1038800014	C	YARYS LISBETH ESPITIA ATENCIA	0	YARYSLISBETH3086@HOTMAIL.COM	 CRA 27  26 D 50 BRR LOS ALPES		2023-04-21 00:00:00-05	A	2
74	36518617	C	INES LUCIA HERNANDEZ  GALVIS	0	.	 CR 18 A 36 BIS 1 11		2023-04-18 00:00:00-05	A	2
75	6885019	C	CESAR MANUEL NARVAEZ SILGADO	0	YO_OPINODELFUTURO@HOTMAIL.COM	 CL 3B 23 32		2023-04-20 00:00:00-05	A	2
76	32678580	C	HELDA MARIA SEPULVEDA VALBUENA	0	ELDASEPULVEDA0@GMAIL.COM	 TRANSVERSAL 14A 42-16		2023-04-20 00:00:00-05	A	2
77	22529542	C	LUZ DARY MENDEZ WILLIAMS	0	FERRECONSTRUCTORESDELCESARADMI@GMAIL.COM	 VRD CR 5 5 69 BRR JORGE ELIECER GAITAN		2023-04-20 00:00:00-05	A	2
78	1067731977	C	YESSICA ELENA MOVILLA RUIZ	0	MOVILLAYESSICA10@GMAIL.COM	 CL 3 5 29 BRR TOSCANO		2023-07-29 00:00:00-05	A	2
79	72193088	C	JANDER  ALEMAN RIPOLL	0	JANDERALEMAN@HOTMAIL.COM	 CRA 2E 42 45		2023-04-24 00:00:00-05	A	2
80	15244464	C	CARLOS RAFAEL MARTINEZ WALDERFORD	0	FERREELMAESTROCONSTRUCTOR@HOTMAIL.COM	 SEC SANTA ISABEL		2023-04-24 00:00:00-05	A	2
81	37946484	C	JAQUELINE PE�A ACU�A	0	.	 CRA 16E 3A 26		2023-04-24 00:00:00-05	A	2
82	72166849	C	JORGE RAFAEL MURGAS LOPEZ	0	JRMURGAS10@GMAIL.COM	 Kr 23 B #  17 a esquina		2023-04-24 00:00:00-05	A	2
\.


--
-- Data for Name: det_factura_detfactura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.det_factura_detfactura (id, consecutivo, cantidad, precio, subtotal, empresa_id, id_factura_id, id_producto_id) FROM stdin;
2	29	1.16	1.16	1.16	4	7	2
3	1	1.00	11.11	11.11	1	17	1
4	11	11.11	11.00	11.11	1	18	4
5	11	11.00	11.11	11.11	4	18	9
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-07-10 14:41:52.825013-05	1	Empresa 1	1	[{"added": {}}]	7	1
2	2024-07-10 19:37:36.702998-05	1	Erik Santiago	1	[{"added": {}}]	8	1
3	2024-07-10 20:03:54.125529-05	1	Producto 1	1	[{"added": {}}]	9	1
4	2024-07-10 21:55:20.684046-05	5	empresa 4	1	[{"added": {}}]	7	1
5	2024-07-10 22:39:37.637062-05	7	observaciones	1	[{"added": {}}]	11	1
6	2024-07-10 22:42:05.379925-05	2	EMPRESA DEMOSTRACION DE ASEO	1	[{"added": {}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	empresa	empresa
8	clientes	clientes
9	productos	productos
10	det_factura	detfactura
11	mae_factura	maefactura
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-07-10 11:44:44.117386-05
2	auth	0001_initial	2024-07-10 11:44:44.199461-05
3	admin	0001_initial	2024-07-10 11:44:44.219479-05
4	admin	0002_logentry_remove_auto_add	2024-07-10 11:44:44.224484-05
5	admin	0003_logentry_add_action_flag_choices	2024-07-10 11:44:44.230489-05
6	contenttypes	0002_remove_content_type_name	2024-07-10 11:44:44.238497-05
7	auth	0002_alter_permission_name_max_length	2024-07-10 11:44:44.243501-05
8	auth	0003_alter_user_email_max_length	2024-07-10 11:44:44.249506-05
9	auth	0004_alter_user_username_opts	2024-07-10 11:44:44.25351-05
10	auth	0005_alter_user_last_login_null	2024-07-10 11:44:44.258515-05
11	auth	0006_require_contenttypes_0002	2024-07-10 11:44:44.260516-05
12	auth	0007_alter_validators_add_error_messages	2024-07-10 11:44:44.26452-05
13	auth	0008_alter_user_username_max_length	2024-07-10 11:44:44.27553-05
14	auth	0009_alter_user_last_name_max_length	2024-07-10 11:44:44.280535-05
15	auth	0010_alter_group_name_max_length	2024-07-10 11:44:44.28654-05
16	auth	0011_update_proxy_permissions	2024-07-10 11:44:44.291545-05
17	auth	0012_alter_user_first_name_max_length	2024-07-10 11:44:44.295548-05
18	sessions	0001_initial	2024-07-10 11:44:44.311563-05
19	empresa	0001_initial	2024-07-10 14:28:00.0982-05
20	clientes	0001_initial	2024-07-10 14:28:00.114214-05
21	productos	0001_initial	2024-07-10 14:28:00.126226-05
22	mae_factura	0001_initial	2024-07-10 14:28:00.142239-05
23	det_factura	0001_initial	2024-07-10 14:28:00.163259-05
24	empresa	0002_alter_empresa_empresa	2024-07-10 19:10:51.940199-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
4dl16i77aiggnavlv73u9ete7uqpiakn	.eJxVjMsOwiAQRf-FtSE8LFCX7vsNZGYYpGogKe3K-O_apAvd3nPOfYkI21ri1nmJcxIXocXpd0OgB9cdpDvUW5PU6rrMKHdFHrTLqSV-Xg_376BAL99aETDZoJxToKzR6D0b4swB_ADoxmRYW-fPITuGlA2NaPPAjOiM9izeH_VDOL0:1sRkcN:KoGixatxV-ffB6S2vtF_A2d_FLU2Lju4Adthxn_Ho3Y	2024-07-24 22:37:15.345661-05
\.


--
-- Data for Name: empresa_empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresa_empresa (id, empresa, nombre, estado) FROM stdin;
1	1007952577	Empresa 1	A
2	1	EMPRESA DEMOSTRACION FINANCIERA	A
3	2	EMPRESA DEMOSTRACION TERPEL	I
4	3	EMPRESA DEMOSTRACION DE ASEO	A
5	4	empresa 4	A
\.


--
-- Data for Name: mae_factura_maefactura; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.mae_factura_maefactura (id, numero, fehca_creacion, observaciones, total, fecha_auditoria, cliente_id, empresa_id) FROM stdin;
7	101110	2024-07-10 22:39:37.636061-05	observaciones	2.12	2024-07-10 22:39:37.636061-05	10	4
17	121	2024-07-11 07:28:13.306456-05	observaciones generales	11.11	2024-07-11 07:28:13.306456-05	1	1
18	121	2024-07-11 07:29:51.605381-05	observaciones generales	11.11	2024-07-11 07:29:51.605381-05	1	1
19	1212	2024-07-11 07:36:53.506038-05	observaciones 2	11.23	2024-07-11 07:36:53.506038-05	2	2
20	2	2024-07-11 07:37:19.159366-05	observaciones de una quinta	1111111.11	2024-07-11 07:37:19.159366-05	2	2
21	11121212	2024-07-11 09:21:50.349227-05	observaciones con select	121212.00	2024-07-11 09:21:50.349227-05	10	2
22	100012321	2024-07-11 09:53:40.018483-05	observaciones nuevo repo	111.11	2024-07-11 09:53:40.018483-05	22	4
\.


--
-- Data for Name: productos_productos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.productos_productos (id, producto, nombre, tipo, fotoproducto, fecha_creacion, estado, empresa_id) FROM stdin;
1	10001	Producto 1	M	productos/sql_server.png	2024-07-10 20:03:54.123526-05	A	4
2	1391	ALAMBRE BRILLANTE  1.00MM	M		2022-03-17 00:00:00-05	A	1
3	100101	ALAMBRE BRILLANTE  CAL 3.40 mm	M		2022-03-17 00:00:00-05	A	1
4	100201	ALAMBRE BRILLANTE  CAL 4.5 mm	M		2022-03-17 00:00:00-05	A	1
5	100301	ALAMBRE BRILLANTE  CAL 5.40 mm	D		2022-03-17 00:00:00-05	A	1
6	100401	ALAMBRE BRILLANTE CAL 20	D		2022-03-17 00:00:00-05	A	1
7	100501	ALAMBRE BRILLANTE DELGADO CAL 13	D		2022-03-17 00:00:00-05	A	1
8	100601	ALAMBRE BRILLANTE DELGADO CAL 14	M		2022-03-17 00:00:00-05	A	1
9	100701	ALAMBRE BRILLANTE DELGADO CAL 14.5	M		2022-03-17 00:00:00-05	A	1
10	100801	ALAMBRE BRILLANTE DELGADO CAL 15	M		2022-10-19 00:00:00-05	A	1
11	100901	ALAMBRE BRILLANTE FINO CAL 18	M		2022-03-17 00:00:00-05	A	1
12	101801	ALAMBRE BRILLANTE GRUESO CAL 10	M		2022-03-17 00:00:00-05	A	1
13	101901	ALAMBRE BRILLANTE GRUESO CAL 10.5	M		2022-03-17 00:00:00-05	A	1
14	102001	ALAMBRE BRILLANTE GRUESO CAL 11	M		2022-03-17 00:00:00-05	A	1
15	102101	ALAMBRE BRILLANTE GRUESO CAL 12	M		2022-03-17 00:00:00-05	A	1
16	101001	ALAMBRE BRILLANTE GRUESO CAL 4	M		2022-03-17 00:00:00-05	A	1
17	101101	ALAMBRE BRILLANTE GRUESO CAL 5	T		2022-03-17 00:00:00-05	A	1
18	101201	ALAMBRE BRILLANTE GRUESO CAL 5.4	T		2022-03-17 00:00:00-05	A	1
19	101301	ALAMBRE BRILLANTE GRUESO CAL 5.58	T		2022-03-17 00:00:00-05	A	1
20	101401	ALAMBRE BRILLANTE GRUESO CAL 6	M		2022-03-17 00:00:00-05	A	1
21	101501	ALAMBRE BRILLANTE GRUESO CAL 7	M		2022-03-17 00:00:00-05	A	1
22	101601	ALAMBRE BRILLANTE GRUESO CAL 8	M		2022-03-17 00:00:00-05	A	1
23	101701	ALAMBRE BRILLANTE GRUESO CAL 9	M		2022-03-17 00:00:00-05	A	1
24	102301	ALAMBRE BRILLANTE RETREFILADO CAL 16	T		2022-03-17 00:00:00-05	A	1
25	102401	ALAMBRE BRILLANTE RETREFILADO CAL 17	T		2022-03-17 00:00:00-05	A	1
26	102201	ALAMBRE BRILLANTE SEMIACERADO CAL 10	T		2022-03-17 00:00:00-05	A	1
27	200101	ALAMBRE DE PUAS 12.5 X 200 M	T		2022-03-17 00:00:00-05	A	1
28	200201	ALAMBRE DE PUAS 12.5 X 330 M	T		2022-03-17 00:00:00-05	A	1
29	200301	ALAMBRE DE PUAS 12.5 X 350 M	T		2022-03-17 00:00:00-05	A	1
30	200401	ALAMBRE DE PUAS 12.5 X 400 M	M		2022-03-17 00:00:00-05	A	1
31	200501	ALAMBRE DE PUAS 14 X 200 M	M		2022-03-17 00:00:00-05	A	1
32	00100039	CALIZA ALTA	M		2023-07-10 00:00:00-05	A	3
33	100001	CEMENTO HIDRAH  TIPO USO GENERAL (UG) X 50 KG	T		2023-06-23 00:00:00-05	A	3
34	100002	CEMENTO HIDRAH  TIPO USO GENERAL ((UG) X 42,5 KG	T		2023-05-29 00:00:00-05	A	3
35	100003	CEMENTO HIDRAH  TIPO USO GENERAL (UG) X 21,25 KG	T		2022-11-23 00:00:00-05	A	3
36	100004	CEMENTO ART TIPO  (ART) 42 5 KG	M		2022-11-23 00:00:00-05	A	3
37	100005	CEMENTO ART GRANEL 34 TON	M		2022-11-23 00:00:00-05	A	3
38	100006	CEMENTO ESTRUCTURAL (EST) 42,5 KG	M		2023-07-11 00:00:00-05	A	3
39	100007	CEMENTO ESTRUCTURAL (EST) 21,25 KG	M		2022-11-23 00:00:00-05	A	3
40	100008	CEMENTO HIDRAULICO TIPO UG TOPEX (UG) TOPEX 50 KG	M		2023-01-23 00:00:00-05	A	3
41	100010	CEMENTO HIDRAULICO TIPO UG TOPEX (UG) TOPEX 42,5 KG	M		2023-07-11 00:00:00-05	A	3
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: clientes_clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clientes_clientes_id_seq', 82, true);


--
-- Name: det_factura_detfactura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.det_factura_detfactura_id_seq', 5, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 6, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: empresa_empresa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empresa_empresa_id_seq', 5, true);


--
-- Name: mae_factura_maefactura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.mae_factura_maefactura_id_seq', 22, true);


--
-- Name: productos_productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_productos_id_seq', 41, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: clientes_clientes clientes_clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes_clientes
    ADD CONSTRAINT clientes_clientes_pkey PRIMARY KEY (id);


--
-- Name: det_factura_detfactura det_factura_detfactura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.det_factura_detfactura
    ADD CONSTRAINT det_factura_detfactura_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: empresa_empresa empresa_empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa_empresa
    ADD CONSTRAINT empresa_empresa_pkey PRIMARY KEY (id);


--
-- Name: mae_factura_maefactura mae_factura_maefactura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mae_factura_maefactura
    ADD CONSTRAINT mae_factura_maefactura_pkey PRIMARY KEY (id);


--
-- Name: productos_productos productos_productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_productos
    ADD CONSTRAINT productos_productos_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: clientes_clientes_empresa_id_b04b2164; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX clientes_clientes_empresa_id_b04b2164 ON public.clientes_clientes USING btree (empresa_id);


--
-- Name: det_factura_detfactura_empresa_id_7a70697a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX det_factura_detfactura_empresa_id_7a70697a ON public.det_factura_detfactura USING btree (empresa_id);


--
-- Name: det_factura_detfactura_id_factura_id_8bb8ffe1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX det_factura_detfactura_id_factura_id_8bb8ffe1 ON public.det_factura_detfactura USING btree (id_factura_id);


--
-- Name: det_factura_detfactura_id_producto_id_62de701c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX det_factura_detfactura_id_producto_id_62de701c ON public.det_factura_detfactura USING btree (id_producto_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: mae_factura_maefactura_cliente_id_a46c17fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mae_factura_maefactura_cliente_id_a46c17fa ON public.mae_factura_maefactura USING btree (cliente_id);


--
-- Name: mae_factura_maefactura_empresa_id_bf4e8c18; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX mae_factura_maefactura_empresa_id_bf4e8c18 ON public.mae_factura_maefactura USING btree (empresa_id);


--
-- Name: productos_productos_empresa_id_d0a7cebc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX productos_productos_empresa_id_d0a7cebc ON public.productos_productos USING btree (empresa_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: clientes_clientes clientes_clientes_empresa_id_b04b2164_fk_empresa_empresa_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clientes_clientes
    ADD CONSTRAINT clientes_clientes_empresa_id_b04b2164_fk_empresa_empresa_id FOREIGN KEY (empresa_id) REFERENCES public.empresa_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: det_factura_detfactura det_factura_detfactu_empresa_id_7a70697a_fk_empresa_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.det_factura_detfactura
    ADD CONSTRAINT det_factura_detfactu_empresa_id_7a70697a_fk_empresa_e FOREIGN KEY (empresa_id) REFERENCES public.empresa_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: det_factura_detfactura det_factura_detfactu_id_factura_id_8bb8ffe1_fk_mae_factu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.det_factura_detfactura
    ADD CONSTRAINT det_factura_detfactu_id_factura_id_8bb8ffe1_fk_mae_factu FOREIGN KEY (id_factura_id) REFERENCES public.mae_factura_maefactura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: det_factura_detfactura det_factura_detfactu_id_producto_id_62de701c_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.det_factura_detfactura
    ADD CONSTRAINT det_factura_detfactu_id_producto_id_62de701c_fk_productos FOREIGN KEY (id_producto_id) REFERENCES public.productos_productos(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mae_factura_maefactura mae_factura_maefactu_cliente_id_a46c17fa_fk_clientes_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mae_factura_maefactura
    ADD CONSTRAINT mae_factura_maefactu_cliente_id_a46c17fa_fk_clientes_ FOREIGN KEY (cliente_id) REFERENCES public.clientes_clientes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mae_factura_maefactura mae_factura_maefactu_empresa_id_bf4e8c18_fk_empresa_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mae_factura_maefactura
    ADD CONSTRAINT mae_factura_maefactu_empresa_id_bf4e8c18_fk_empresa_e FOREIGN KEY (empresa_id) REFERENCES public.empresa_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_productos productos_productos_empresa_id_d0a7cebc_fk_empresa_empresa_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_productos
    ADD CONSTRAINT productos_productos_empresa_id_d0a7cebc_fk_empresa_empresa_id FOREIGN KEY (empresa_id) REFERENCES public.empresa_empresa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

