# Generated by Django 4.1.5 on 2024-07-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('empresa', '0001_initial'),
        ('mae_factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae_factura.maefactura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
            options={
                'ordering': ['consecutivo'],
            },
        ),
    ]
