# Generated by Django 4.1.5 on 2024-07-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaeFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fehca_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=300)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_auditoria', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
