# Generated by Django 4.1.5 on 2024-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
