# Generated by Django 4.1.5 on 2024-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.IntegerField(),
        ),
    ]
